#!/bin/ksh

# Directories
WORKINGDIR=/home/romain/Projects/dartagnan/Run_slurm/user/romain/NWA-RE.FRWTYPEG/
DARTMNGDIR=/home/romain/Projects/dartagnan/Run_slurm/

# Number of ensemble members to run
NMEMBERS=1

# Starting date
REFDATE=19000101
STARTDATE=20110101

# Analysis step (days)
DT_ANA=1

# Simulation name
SIMU=NWA-RE.FRWTYPEG

# start at cycle nstart
NSTART=1
# end at cycle ncycles
NCYCLES=7

# Computation directory
SCRATCHDIR=/t0/scratch/romain/dart/tmpdir_NWA-RE.FRWTYPEG/
DATADIR=/t0/scratch/romain/DART/Data/

#-------------------------------------------------------
# QUEUEING SYSTEM PARAMETERS
#-------------------------------------------------------

CLUSTER=triton

# Time limit
TLIM_ROMS=3:00:00
TLIM_DART=3:00:00

# TRITON OPTIONS
# Type of triton cores to use
# (Don't use generic -triton- for dart)
TYPENODE_ROMS=triton
TYPENODE_DART=triton16

# YELLOWSTONE OPTIONS
PROJECT=
QUEUE=regular

#-------------------------------------------------------
# DART PARAMETERS
#-------------------------------------------------------

# Number of core for analysis
NCORES_DART=48

# start analysis at cycle nstart_ana
NSTART_ANA=60

# Observation files
OBS_DIR=${DATADIR}/ObsData/SST/obsSEQ/
OBS_PREF=obs_seq.sst1.

#-------------------------------------------------------
# ROMS PARAMETERS
#-------------------------------------------------------

# Number of core for forward
NCORES_ROMS=96
ITILE=12
JTILE=8

# Time step
DT=200

# SPIN-UP
DT_SPIN=200
NCYCLES_SPIN=5

# Output step (days)
DT_OUT=1

# Filter output step (days)
DT_FILT=1


# File parameters
FORCINGDIR=${DATADIR}/Inputs/Forcings/Perturbed/CorrectDx/
FORCINGPREF=drowned_MERRA_
FORCINGSUFF=_3hours_

GRIDFILE=/t0/scratch/romain/inputs/NWA_grd_newwtypechl.nc
INITDIR=${DATADIR}/Inputs/Init/HYCOM_ClimCore2/
INITFILE=HYCOM_GLBa0.08_2011_001_ClimCore2_NWA_init.nc

CLIMFILE=${DATADIR}/Inputs/CLM-NWA/HYCOM_GLBa0.08_monthly_clim_NWA_2011.nc
BRYFILE=${DATADIR}/Inputs/BC-NWA/HYCOM_GLBa0.08_bdry_NWA_2011.nc
RUNOFFILE=${DATADIR}/Inputs/Runoff/runoff_NWA_daitren_clim.nc
TIDESFILE=${DATADIR}/Inputs/Tides/NWA_tides_otps.nc
SSSREFILE=${DATADIR}/Inputs/SSS/sss_monthly_climato_flooded.nc


#-------------------------------------------------------
# EXECUTABLES
#-------------------------------------------------------

if [ ${CLUSTER} = "triton" ] ; then
   SUBMIT=sbatch
   RUN="srun --cpu_bind=rank"
elif [ ${CLUSTER} = "yellowstone" ] ; then
   SUBMIT=bsub
   RUN=mpirun.lsf
fi
