#!/bin/ksh

# Directories
WORKINGDIR=/glade/u/home/romaines/Projects/dartagnan/user/romain/NWA-RE.REANA20/
DARTMNGDIR=/glade/u/home/romaines/Projects/dartagnan/

# Number of ensemble members to run
NMEMBERS=30

# Starting date
REFDATE=19000101
STARTDATE=20110101

# Analysis step (days)
DT_ANA=1

# Simulation name
SIMU=NWA-RE.REANA20

# start at cycle nstart
NSTART=1
# end at cycle ncycles
NCYCLES=3

# Computation directory
SCRATCHDIR=/glade/scratch/romaines//dart/tmpdir_NWA-RE.REANA20/
DATADIR=/glade/scratch/dussin/romain/

#-------------------------------------------------------
# QUEUEING SYSTEM PARAMETERS
#-------------------------------------------------------

CLUSTER=yellowstone

# Time limit
TLIM_ROMS=0:10
TLIM_DART=0:30

# TRITON OPTIONS
if [ ${CLUSTER} = "triton" ] ; then
   # Type of triton cores to use
   # (Don't use generic -triton- for dart)
   TYPENODE_ROMS=triton24
   TYPENODE_DART=triton24

elif [ ${CLUSTER} = "yellowstone" ] ; then
   # YELLOWSTONE OPTIONS
   TYPENODE_DART=yellowstone
   PROJECT=URTG0011
   QUEUE=regular
fi

#-------------------------------------------------------
# DART PARAMETERS
#-------------------------------------------------------

# Number of core for analysis
NCORES_DART=32

# start analysis at cycle nstart_ana
NSTART_ANA=2

# Observation files
OBS_DIR=${DATADIR}/SST_GTSPP/obsSEQ/Serr05/
OBS_PREF=obs_seq.sst_gtspp.

# Inflation
INFLATION=true


#-------------------------------------------------------
# ROMS PARAMETERS
#-------------------------------------------------------

# Number of core for forward
NCORES_ROMS=80
ITILE=10
JTILE=8

# Time step
DT=200

# SPIN-UP
DT_SPIN=200
NCYCLES_SPIN=5

# Output step (days)
DT_OUT=1

# Filter output step (days)
DT_FILT=1


# File parameters
FORCINGDIR=${DATADIR}/CorrectDx/
FORCINGPREF=drowned_MERRA_
FORCINGSUFF=_3hours_

GRIDFILE=${DATADIR}/NWA_grd_newwtypechl.nc
INITDIR=${DATADIR}/Init/HYCOM_ClimCore2/
INITFILE=HYCOM_GLBa0.08_2011_001_ClimCore2_NWA_init.nc

CLIMFILE=${DATADIR}/CLM-NWA/HYCOM_GLBa0.08_monthly_clim_NWA_2011.nc
BRYFILE=${DATADIR}/BC-NWA/HYCOM_GLBa0.08_bdry_NWA_2011.nc
RUNOFFILE=${DATADIR}/Runoff/runoff_NWA_daitren_clim.nc
TIDESFILE=${DATADIR}/Tides/NWA_tides_otps.nc
SSSREFILE=${DATADIR}/SSS/sss_monthly_climato_flooded.nc


#-------------------------------------------------------
# EXECUTABLES
#-------------------------------------------------------

if [ ${CLUSTER} = "triton" ] ; then
   SUBMIT=sbatch
   RUN="srun --cpu_bind=rank -n $NCORES"
elif [ ${CLUSTER} = "yellowstone" ] ; then
   SUBMIT=bsub
   RUN=mpirun.lsf
fi
