#!/bin/bash

#BSUB -n 10
#BSUB -q geyser
#BSUB -o <CURRENTDIR>/Logs/roms_nc4diags_<SIMU>.%J.out
#BSUB -e <CURRENTDIR>/Logs/roms_nc4diags_<SIMU>.%J.err
#BSUB -J roms_diags_nc4diags_<SIMU>
#BSUB -W 00:30
#BSUB -P <PROJECTCODE>

# Load simulation parameters
. ./parameters
. ./functions.sh

module load nco
module load parallel

cd ${SCRATCHDIR}/Outputs/Diags/

ls *.nc | parallel "ncks -4 -L 1 {} {}4"
rm *.nc

exit 0
