#!/bin/bash
#SBATCH -n 1
#SBATCH --time=0:10:00
#SBATCH -J analysis
#SBATCH --dependency=afterok<DEPLIST>
#SBATCH --error=analysis.%J.err 
#SBATCH --output=analysis.%J.out
#SBATCH -p triton24

set -x

CONTROLDIR=<CDIR>
thiscycle=<CYCLE>
this_job_id=${SLURM_JOB_ID}

#------------------------------------------------------------------------------------
# create all necessary inputs and namelists
#------------------------------------------------------------------------------------

#------------------------------------------------------------------------------------
# run the analysis
#------------------------------------------------------------------------------------

#   srun --cpu_bind=rank -n <NCORES> ./filter 

# test
sleep 10
success=1

#------------------------------------------------------------------------------------
# if analysis successful, submit next cycle
#------------------------------------------------------------------------------------

if [ $success == 1 ] ; then
   nextcycle=$(( $thiscycle + 1 ))
   ssh node0 "cd $CONTROLDIR ; ./submit_cycle.ksh $nextcycle"
else 
   echo "Assimilation cycle # $thiscycle failed"
fi
