#!/bin/bash
#SBATCH -n 1
#SBATCH --time=0:10:00
#SBATCH -J roms_advance_<MEMBER>
#SBATCH --error=roms_advance_<MEMBER>.%J.err 
#SBATCH --output=roms_advance_<MEMBER>.%J.out
#SBATCH -p triton24

#CONTROLDIR=<CDIR>

set -x

#------------------------------------------------------------------------------------
# add job-id to list
#------------------------------------------------------------------------------------

this_member=<MEMBER>
this_job_id=${SLURM_JOB_ID}


#------------------------------------------------------------------------------------
# run the code
#------------------------------------------------------------------------------------


#   srun --cpu_bind=rank -n <NCORES> ./oceanM <NAMELIST>  > log.<JOB>
#   srun --cpu_bind=rank -n 1 echo $(hostname) $this_member $this_job_id > log.$this_member

sleep 15
