#!/bin/bash
#SBATCH -n 1
#SBATCH --time=0:10:00
#SBATCH -J analysis
#SBATCH --dependency=afterok:<DEPLIST>
#SBATCH --error=analysis.%J.err 
#SBATCH --output=analysis.%J.out
#SBATCH -p triton24

#CONTROLDIR=<CDIR>

set -x

#------------------------------------------------------------------------------------
# add job-id to list
#------------------------------------------------------------------------------------

this_job_id=${SLURM_JOB_ID}


#------------------------------------------------------------------------------------
# run the code
#------------------------------------------------------------------------------------


#   srun --cpu_bind=rank -n <NCORES> ./oceanM <NAMELIST>  > log.<JOB>
#   srun --cpu_bind=rank -n 1 echo $(hostname) $this_member $this_job_id > log.$this_member

sleep 60
