#!/bin/ksh

# Directories
WORKINGDIR=/home/romain/Projects/dartagnan/Run_slurm/user/romain/NWA-RE.FRSTO05/
DARTMNGDIR=/home/romain/Projects/dartagnan/Run_slurm/

# Number of ensemble members to run
NMEMBERS=1

# Starting date
REFDATE=19000101
STARTDATE=20110101

# Analysis step (days)
DT_ANA=1
DT_OBS=5

# Simulation name
SIMU=NWA-RE.FRSTO04

# start at cycle nstart
NSTART=1
# end at cycle ncycles
NCYCLES=183

# Computation directory
SCRATCHDIR=/t0/scratch/romain/dart/tmpdir_NWA-RE.FRSTO05/
DATADIR=/t0/scratch/romain/DART/Data/

#-------------------------------------------------------
# QUEUEING SYSTEM PARAMETERS
#-------------------------------------------------------

CLUSTER=triton

# Time limit
TLIM_ROMS=30:00
TLIM_DART=30:00

# TRITON OPTIONS
if [ ${CLUSTER} = "triton" ] ; then
   # Type of triton cores to use
   # (Don't use generic -triton- for dart)
   TYPENODE_ROMS=triton24
   TYPENODE_DART=triton24

elif [ ${CLUSTER} = "yellowstone" ] ; then
   # YELLOWSTONE OPTIONS
   TYPENODE_DART=yellowstone
   PROJECT=URTG0011
   QUEUE=regular
fi

#-------------------------------------------------------
# DART PARAMETERS
#-------------------------------------------------------

# Number of core for analysis
NCORES_DART=24

# start analysis at cycle nstart_ana
NSTART_ANA=366

# Observation files
OBS_DIR=${DATADIR}/ObsData/SST_GTSPP/obsSEQ/
OBS_PREF=obs_seq.sst_gtspp.

# Inflation
INF_INI=1.02
INF_SD_INI=0.6

#-------------------------------------------------------
# ROMS PARAMETERS
#-------------------------------------------------------

# Number of core for forward
NCORES_ROMS=144
ITILE=12
JTILE=12

# Time step
DT=200

# SPIN-UP
DT_SPIN=200
NCYCLES_SPIN=5

# Output step (days)
DT_OUT=1

# Filter output step (days)
DT_FILT=1


# File parameters
FORCINGDIR=${DATADIR}/Inputs/Forcings/Perturbed/CorrectDx/
FORCINGPREF=drowned_MERRA_
FORCINGSUFF=_3hours_

GRIDFILE=/t0/scratch/romain/inputs/NWA_grd_newwtypechl.nc
NUDGCOEF=/t0/scratch/romain/inputs/NWA_nudging_coef.nc
INITDIR=${DATADIR}/Inputs/Init/HYCOM_ClimCore2/
INITFILE=HYCOM_GLBa0.08_2011_001_ClimCore2_NWA_init.nc

CLIMFILE=${DATADIR}/Inputs/CLM-NWA/HYCOM_GLBa0.08_monthly_clim_NWA_2011.nc
BRYFILE=${DATADIR}/Inputs/BC-NWA/HYCOM_GLBa0.08_bdry_NWA_2011.nc
RUNOFFILE=${DATADIR}/Inputs/Runoff/runoff_NWA_daitren_clim.nc
TIDESFILE=${DATADIR}/Inputs/Tides/NWA_tides_otps.nc
SSSREFILE=${DATADIR}/Inputs/SSS/sss_monthly_climato_flooded.nc


#-------------------------------------------------------
# EXECUTABLES
#-------------------------------------------------------

if [ ${CLUSTER} = "triton" ] ; then
   SUBMIT="sbatch --reservation=dart"
   RUN="srun --cpu_bind=rank"
   declare -a frontnode=(node0)
elif [ ${CLUSTER} = "yellowstone" ] ; then
   SUBMIT=bsub
   RUN=mpirun.lsf
   declare -a frontnode=(yslogin1 yslogin2 yslogin3 yslogin4 yslogin5 yslogin6)
fi
