#!/bin/ksh

# Directories
WORKINGDIR=/glade/u/home/romaines/Projects/dartagnan/Run_slurm/user/romain/NWA-RE.REANA33/
DARTMNGDIR=/glade/u/home/romaines/Projects/dartagnan/Run_slurm/

# Number of ensemble members to run
NMEMBERS=30

# Starting date
REFDATE=19000101
STARTDATE=20110101

# Analysis step (days)
DT_ANA=1
DT_OBS=5

# Simulation name
SIMU=NWA-RE.REANA33

# start at cycle nstart
NSTART=1
# end at cycle ncycles
NCYCLES=30

# Computation directory
SCRATCHDIR=/glade/scratch/romaines//dart/tmpdir_NWA-RE.REANA33/
DATADIR=/glade/scratch/dussin/romain/

#-------------------------------------------------------
# QUEUEING SYSTEM PARAMETERS
#-------------------------------------------------------

CLUSTER=yellowstone

# Time limit
TLIM_ROMS=0:20
TLIM_DART=0:30

# TRITON OPTIONS
if [ ${CLUSTER} = "triton" ] ; then
   # Type of triton cores to use
   # (Don't use generic -triton- for dart)
   TYPENODE_ROMS=triton24
   TYPENODE_DART=triton24

elif [ ${CLUSTER} = "yellowstone" ] ; then
   # YELLOWSTONE OPTIONS
   TYPENODE_DART=yellowstone
   PROJECT=URTG0008
   QUEUE=economy
fi

#-------------------------------------------------------
# DART PARAMETERS
#-------------------------------------------------------

# Number of core for analysis
NCORES_DART=80

# start analysis at cycle nstart_ana
NSTART_ANA=50

# Observation files
OBS_DIR=/glade/p/work/romaines/Data/ObsData/SST_GTSPP/obsSEQ/Serr03Terr07thinSSTerr015_ST5days/
OBS_PREF=obs_seq.sst.

# Inflation
INF_INI=1.02
INF_SD_INI=0.6

#-------------------------------------------------------
# ROMS PARAMETERS
#-------------------------------------------------------

# Number of core for forward
NCORES_ROMS=80
ITILE=10
JTILE=8

# Time step
DT=200

# SPIN-UP
DT_SPIN=200
NCYCLES_SPIN=5

# Output step (days)
DT_OUT=1

# Filter output step (days)
DT_FILT=1


# File parameters
FORCINGDIR=${DATADIR}/Forcings/
FORCINGPREF=drowned_MERRA_
FORCINGSUFF=_3hours_

GRIDFILE=${DATADIR}/NWA_grd_newwtypechl.nc
NUDGCOEF=${DATADIR}/NWA_nudging_coef.nc
INITDIR=/glade/p/work/romaines/Data/Init/
INITFILE=HYCOM_GLBa0.08_2011_001_ic_NWA.nc

CLIMFILE=${DATADIR}/CLM-NWA/HYCOM_GLBa0.08_monthly_clim_NWA_2011.nc
BRYFILE=${DATADIR}/BC-NWA/HYCOM_GLBa0.08_bdry_NWA_2011.nc
RUNOFFILE=${DATADIR}/Runoff/runoff_NWA_daitren_clim.nc
TIDESFILE=${DATADIR}/Tides/NWA_tides_otps.nc
SSSREFILE=${DATADIR}/SSS/sss_monthly_climato_flooded.nc

#-------------------------------------------------------
# EXECUTABLES
#-------------------------------------------------------

if [ ${CLUSTER} = "triton" ] ; then
   SUBMIT=sbatch
   RUN="srun --cpu_bind=rank"
   declare -a frontnode=(node0)
elif [ ${CLUSTER} = "yellowstone" ] ; then
   SUBMIT=bsub
   RUN=mpirun.lsf
   declare -a frontnode=(yslogin1 yslogin2 yslogin3 yslogin4 yslogin5 yslogin6)
fi
