#!/bin/ksh

WORKINGDIR=/t6/workdir/romain/dartagnan/Run_slurm/user/romain/NWA-RE.REANA02/
DARTMNGDIR=/t6/workdir/romain/dartagnan/Run_slurm/

# Type of triton cores to use
TYPENODE=triton16

# Number of ensemble members to run
NMEMBERS=30

# Starting date
REFDATE=19000101
STARTDATE=20110101

# Analysis step (days)
DT_ANA=1

# Simulation name
SIMU=NWA-RE.REANA02

# start at cycle nstart
NSTART=2
# end at cycle ncycles
NCYCLES=31

# Computation directory
SCRATCHDIR=/t0/scratch/romain/dart/tmpdir_NWA-RE.REANA02/
DATADIR=/t0/scratch/romain/DART/Data/

#--------------------------------------------------
# DART PARAMETERS
#--------------------------------------------------

# Number of core for analysis
NCORES_DART=48

# start analysis at cycle nstart_ana
NSTART_ANA=10

#--------------------------------------------------
# ROMS PARAMETERS
#--------------------------------------------------

# Number of core for forward
NCORES_ROMS=48
ITILE=6
JTILE=8

# Time step
DT=180

# Output step (days)
DT_OUT=1

# File parameters
FORCINGDIR=${DATADIR}/Inputs/Force/
FORCINGPREF=drowned_MERRA_
FORCINGSUFF=_3hours_

GRIDFILE=/t0/scratch/romain/inputs/NWA_grd.nc
INITFILE=${DATADIR}/Inputs/Init/NWA-RD.ClimCore2H01R_y0XXXm01d01.nc

CLIMFILE=${DATADIR}/Inputs/CLM-NWA/HYCOM_GLBa0.08_monthly_clim_NWA_2011.nc
BRYFILE=${DATADIR}/Inputs/BC-NWA/HYCOM_GLBa0.08_bdry_NWA_2011.nc
RUNOFFILE=${DATADIR}/Inputs/Runoff/runoff_NWA_daitren_clim.nc
TIDESFILE=${DATADIR}/Inputs/Tides/NWA_tides_otps.nc
SSSREFILE=${DATADIR}/Inputs/SSS/sss_monthly_climato_flooded.nc



