#!/bin/ksh

WORKINGDIR=/home/bjchoi/dartagnan/Run_slurm/user/bjchoi/NWA-BJC.ENKF14/
DARTMNGDIR=/home/bjchoi/dartagnan/Run_slurm/

# Type of triton cores to use
TYPENODE=triton16

# Number of ensemble members to run
NMEMBERS=30

# Starting date
REFDATE=19000101
STARTDATE=20110101

# Analysis step (days)
DT_ANA=1

# Simulation name
SIMU=NWA-BJC.ENKF14

# start at cycle nstart
NSTART=252
# end at cycle ncycles
NCYCLES=252

# Computation directory
SCRATCHDIR=/t0/scratch/bjchoi/tmpdir_NWA-BJC.ENKF14
DATADIR=/t0/scratch/romain/DART/Data

#--------------------------------------------------
# DART PARAMETERS
#--------------------------------------------------

# Number of core for analysis
NCORES_DART=48

# start analysis at cycle nstart_ana
NSTART_ANA=10

#--------------------------------------------------
# ROMS PARAMETERS
#--------------------------------------------------

# Number of core for forward
NCORES_ROMS=48
ITILE=6
JTILE=8

# Time step
DT=180

# Output step (days)
DT_OUT=1

# File parameters
FORCINGDIR=${DATADIR}/Inputs/Force/
FORCINGPREF=drowned_MERRA_
FORCINGSUFF=_3hours_

GRIDFILE=/t0/scratch/romain/inputs/NWA_grd.nc
INITFILE=/dev/null

CLIMFILE=${DATADIR}/Inputs/CLM-NWA/HYCOM_GLBa0.08_monthly_clim_NWA_2011.nc
BRYFILE=${DATADIR}/Inputs/BC-NWA/HYCOM_GLBa0.08_bdry_NWA_2011.nc
RUNOFFILE=${DATADIR}/Inputs/Runoff/runoff_NWA_daitren_clim.nc
TIDESFILE=${DATADIR}/Inputs/Tides/NWA_tides_otps.nc
SSSREFILE=${DATADIR}/Inputs/SSS/sss_monthly_climato_flooded.nc



